import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export interface ExportOptions {
  filename?: string;
  title?: string;
  userName?: string;
}

const cleanTitle = (title: string): string => {
  let cleaned = title;

  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = title;
  cleaned = tempDiv.textContent || tempDiv.innerText || title;

  cleaned = cleaned.replace(/[\u{1F300}-\u{1F9FF}]/gu, '');
  cleaned = cleaned.replace(/[\u{2600}-\u{26FF}]/gu, '');
  cleaned = cleaned.replace(/[\u{2700}-\u{27BF}]/gu, '');
  cleaned = cleaned.replace(/[^\x00-\x7F]/g, '');

  cleaned = cleaned.replace(/^[^a-zA-Z0-9]+/, '');

  cleaned = cleaned.trim();

  if (cleaned.length > 80) {
    cleaned = cleaned.substring(0, 80) + '...';
  }

  return cleaned || 'Visualization Report';
};

const addHeader = (
  pdf: jsPDF,
  cleanedTitle: string,
  userName: string,
  pageWidth: number,
  isFirstPage: boolean = true
): number => {
  if (isFirstPage) {
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(18);
    const titleLines = pdf.splitTextToSize(cleanedTitle, pageWidth - 20);
    pdf.text(titleLines, pageWidth / 2, 15, { align: 'center' });

    const titleHeight = 15 + (titleLines.length - 1) * 6;

    pdf.setFontSize(10);
    pdf.setTextColor(156, 163, 175);
    const currentDate = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
    pdf.text(`Generated: ${currentDate}`, pageWidth / 2, titleHeight + 8, { align: 'center' });
    pdf.text(`User: ${userName}`, pageWidth / 2, titleHeight + 14, { align: 'center' });

    pdf.setDrawColor(75, 85, 99);
    pdf.setLineWidth(0.5);
    pdf.line(15, titleHeight + 18, pageWidth - 15, titleHeight + 18);

    return titleHeight + 23;
  } else {
    pdf.setFontSize(12);
    pdf.setTextColor(156, 163, 175);
    pdf.text(cleanedTitle, pageWidth / 2, 12, { align: 'center' });

    pdf.setDrawColor(75, 85, 99);
    pdf.setLineWidth(0.3);
    pdf.line(15, 16, pageWidth - 15, 16);

    return 22;
  }
};

const addFooter = (pdf: jsPDF, pageWidth: number, pageHeight: number, pageNum: number, totalPages: number): void => {
  pdf.setFontSize(9);
  pdf.setTextColor(107, 114, 128);
  pdf.text(
    'Generated by Astra Intelligence - RocketHub',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  pdf.setFontSize(8);
  pdf.text(
    `Page ${pageNum} of ${totalPages}`,
    pageWidth / 2,
    pageHeight - 5,
    { align: 'center' }
  );
};

export const exportVisualizationToPDF = async (
  element: HTMLElement,
  options: ExportOptions = {}
): Promise<void> => {
  try {
    const {
      filename = 'visualization',
      title = 'Visualization Report',
      userName = 'User'
    } = options;

    const cleanedTitle = cleanTitle(title);

    const originalWidth = element.scrollWidth;
    const originalHeight = element.scrollHeight;

    const targetWidth = 1200;
    const scale = targetWidth / originalWidth;

    const canvas = await html2canvas(element, {
      scale: scale,
      useCORS: true,
      logging: false,
      backgroundColor: '#1f2937',
      windowWidth: originalWidth,
      windowHeight: originalHeight,
      imageTimeout: 0,
      width: originalWidth,
      height: originalHeight
    });

    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();

    const marginSides = 15;
    const marginBottom = 20;
    const contentWidth = pageWidth - (marginSides * 2);

    const imgWidthMm = contentWidth;
    const imgHeightMm = (canvas.height * contentWidth) / canvas.width;

    const imgData = canvas.toDataURL('image/png', 1.0);

    let yOffset = 0;
    let pageNum = 1;
    const pages: Array<{ isFirst: boolean; yStart: number; height: number }> = [];

    while (yOffset < imgHeightMm) {
      const isFirstPage = pageNum === 1;
      const headerHeight = isFirstPage ? 40 : 22;
      const availableHeight = pageHeight - headerHeight - marginBottom;

      const heightForThisPage = Math.min(availableHeight, imgHeightMm - yOffset);

      pages.push({
        isFirst: isFirstPage,
        yStart: yOffset,
        height: heightForThisPage
      });

      yOffset += heightForThisPage;
      pageNum++;
    }

    const totalPages = pages.length;

    pages.forEach((pageInfo, index) => {
      if (index > 0) {
        pdf.addPage();
      }

      pdf.setFillColor(31, 41, 55);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');

      const headerHeight = addHeader(pdf, cleanedTitle, userName, pageWidth, pageInfo.isFirst);

      const sy = (pageInfo.yStart / imgHeightMm) * canvas.height;
      const sh = (pageInfo.height / imgHeightMm) * canvas.height;
      const sw = canvas.width;

      const tempCanvas = document.createElement('canvas');
      tempCanvas.width = sw;
      tempCanvas.height = sh;
      const tempCtx = tempCanvas.getContext('2d');

      if (tempCtx) {
        tempCtx.drawImage(canvas, 0, sy, sw, sh, 0, 0, sw, sh);
        const pageImgData = tempCanvas.toDataURL('image/png', 1.0);

        pdf.addImage(
          pageImgData,
          'PNG',
          marginSides,
          headerHeight,
          imgWidthMm,
          pageInfo.height,
          undefined,
          'FAST'
        );
      }

      addFooter(pdf, pageWidth, pageHeight, index + 1, totalPages);
    });

    const sanitizedFilename = filename
      .replace(/[^a-z0-9]/gi, '-')
      .replace(/-+/g, '-')
      .toLowerCase();

    const timestamp = new Date().toISOString().split('T')[0];
    const finalFilename = `${sanitizedFilename}-${timestamp}.pdf`;

    pdf.save(finalFilename);

    return Promise.resolve();
  } catch (error) {
    console.error('Failed to export PDF:', error);
    throw new Error('Failed to generate PDF. Please try again.');
  }
};
