export interface FAQItem {
  question: string;
  answer: string;
  category: 'getting-started' | 'chat-modes' | 'visualizations' | 'team' | 'integrations' | 'reports' | 'admin';
}

export const helpFAQ: FAQItem[] = [
  {
    category: 'getting-started',
    question: 'What is Astra Intelligence?',
    answer: 'Astra Intelligence is your AI assistant connected to all your team\'s data. Ask questions, get insights, create visualizations, and collaborate with your team - all powered by AI that understands your company\'s information.'
  },
  {
    category: 'getting-started',
    question: 'How do I ask Astra a question?',
    answer: 'Simply type your question in the chat input at the bottom of the screen and press Enter or click Send. Astra will analyze your data and provide insights based on your question.'
  },
  {
    category: 'getting-started',
    question: 'What kind of questions can I ask?',
    answer: 'You can ask about your company data, request visualizations, search through documents, analyze trends, or get summaries. Try questions like "What are our top priorities?" or "Show me email trends from last month".'
  },
  {
    category: 'chat-modes',
    question: 'What\'s the difference between Private and Team chat?',
    answer: 'Private mode is just for you - your questions and Astra\'s responses are only visible to you. Team mode is collaborative - everyone on your team can see the conversation and contribute.'
  },
  {
    category: 'chat-modes',
    question: 'When should I use Team mode?',
    answer: 'Use Team mode when you want to collaborate with your team on insights, share discoveries, or have group discussions with AI assistance. It\'s great for team meetings, brainstorming, or sharing important findings.'
  },
  {
    category: 'chat-modes',
    question: 'Can I switch between Private and Team mode?',
    answer: 'Yes! Click the "Private" or "Team" button at the top of the chat to switch modes. Each mode has its own conversation history that stays separate.'
  },
  {
    category: 'visualizations',
    question: 'How do I create a visualization?',
    answer: 'Ask Astra to create a chart or visualization in your question. For example: "Show me a chart of email volume over time" or "Visualize our team\'s document activity". Astra will generate an interactive visualization based on your data.'
  },
  {
    category: 'visualizations',
    question: 'Who can see my visualizations?',
    answer: 'Only you can see visualizations you create. Even in Team mode, visualizations are private to the person who requested them. You can export them as PDFs to share with others.'
  },
  {
    category: 'visualizations',
    question: 'Can I save visualizations?',
    answer: 'Yes! When viewing a visualization, click the bookmark icon to save it. Your saved visualizations appear in your sidebar for easy access later.'
  },
  {
    category: 'visualizations',
    question: 'How do I export a visualization?',
    answer: 'Open any visualization and click the "Export as PDF" button. This creates a downloadable PDF that you can share or keep for your records.'
  },
  {
    category: 'team',
    question: 'How do I mention someone in Team chat?',
    answer: 'Type @ followed by their name in Team mode. You\'ll see a list of team members to choose from. Mentioned users will receive a notification.'
  },
  {
    category: 'team',
    question: 'How do notifications work?',
    answer: 'You\'ll receive notifications when someone mentions you in Team chat or when there\'s important team activity. Click the bell icon in the header to view your notifications.'
  },
  {
    category: 'team',
    question: 'Can I see who\'s on my team?',
    answer: 'Yes! Click your profile picture or the team icon in the header to see all team members. You can view their roles and contact information there.'
  },
  {
    category: 'reports',
    question: 'What are Reports?',
    answer: 'Reports are a dedicated space where you can view scheduled reports and insights generated by your team admins. They provide regular summaries and analyses of your team\'s data.'
  },
  {
    category: 'reports',
    question: 'How do I access Reports?',
    answer: 'Click the "Reports" button in the left sidebar to view all available reports. You can filter by date and view detailed insights for each report.'
  },
  {
    category: 'reports',
    question: 'Can I create my own reports?',
    answer: 'Regular team members can view reports but not create scheduled ones. Admins can set up automated reports that run on a schedule. However, you can always ask Astra to generate custom insights anytime!'
  },
  {
    category: 'integrations',
    question: 'What is Google Drive integration?',
    answer: 'Google Drive integration allows Astra to access and analyze your team\'s Google Drive documents. Once connected, you can ask questions about your docs, sheets, and slides.'
  },
  {
    category: 'integrations',
    question: 'Is my Google Drive data secure?',
    answer: 'Yes! We only access files you grant permission to, and all data is encrypted. Your documents are processed securely and stored safely in your team\'s private database.'
  },
  {
    category: 'integrations',
    question: 'Can I disconnect Google Drive?',
    answer: 'Yes, admins can disconnect Google Drive at any time from Team Settings. This will stop syncing new documents, but previously synced data will remain available to your team.'
  },
  {
    category: 'admin',
    question: 'How do I invite team members?',
    answer: 'As an admin, click on the Team Members section and then click "Invite Member". Enter their email address and they\'ll receive an invitation to join your team.'
  },
  {
    category: 'admin',
    question: 'What\'s the difference between Admin and Member roles?',
    answer: 'Admins can invite team members, manage team settings, connect integrations, delete documents, and set up scheduled reports. Members can chat with Astra, create visualizations, and view team data, but have more limited management capabilities.'
  },
  {
    category: 'admin',
    question: 'How do I set up scheduled reports?',
    answer: 'Go to Team Settings and navigate to the Scheduled Reports section. You can create reports that run daily, weekly, or monthly at specific times, asking Astra any question you want automated.'
  },
  {
    category: 'admin',
    question: 'How do I connect Google Drive?',
    answer: 'Go to Team Settings, find the Google Drive section, and click "Connect Google Drive". You\'ll be taken to Google to authorize access, then you can select which folders to sync.'
  },
  {
    category: 'admin',
    question: 'Can I remove team members?',
    answer: 'Yes, admins can remove team members from the Team Members panel. Click the menu next to a member\'s name and select "Remove from Team". Their access will be revoked immediately.'
  }
];

export const faqCategories = {
  'getting-started': {
    title: '🚀 Getting Started',
    description: 'Learn the basics of using Astra'
  },
  'chat-modes': {
    title: '💬 Chat Modes',
    description: 'Understanding Private and Team chat'
  },
  'visualizations': {
    title: '📊 Visualizations',
    description: 'Creating and managing data visualizations'
  },
  'team': {
    title: '👥 Team Collaboration',
    description: 'Working with your team in Astra'
  },
  'reports': {
    title: '📈 Reports',
    description: 'Viewing and understanding reports'
  },
  'integrations': {
    title: '🔗 Integrations',
    description: 'Connecting Google Drive and other services'
  },
  'admin': {
    title: '⚙️ Admin Features',
    description: 'Managing your team and settings'
  }
} as const;
