import { TourStep } from '../components/InteractiveTour';

export const memberTourSteps: TourStep[] = [
  {
    id: 'welcome-chat',
    title: 'Meet Astra, Your AI Assistant',
    description: 'Type any question here and I\'ll help you find answers from your team\'s data. Try asking me to create visualizations or search through your documents!',
    targetSelector: '[data-tour="chat-input"]',
    position: 'top'
  },
  {
    id: 'chat-modes',
    title: 'Private or Team Chat',
    description: 'Use Private mode for personal questions that only you can see. Switch to Team mode when you want everyone to collaborate on insights together.',
    targetSelector: '[data-tour="mode-toggle"]',
    position: 'bottom'
  },
  {
    id: 'reports-view',
    title: 'View Team Reports',
    description: 'Check out scheduled reports and insights generated by your team admins. Reports provide regular summaries and analyses of your team\'s data.',
    targetSelector: '[data-tour="reports-button"]',
    position: 'right'
  },
  {
    id: 'visualizations',
    title: 'Data Visualizations',
    description: 'Ask me to create charts and visualizations! Your visualizations are private to you, even in Team mode. Save your favorites or export them as PDFs.',
    targetSelector: '[data-tour="chat-input"]',
    position: 'top'
  },
  {
    id: 'user-settings',
    title: 'Your Profile & Settings',
    description: 'Click here to manage your profile, adjust notification preferences, and access team settings. You can also restart this tour anytime from here!',
    targetSelector: '[data-tour="user-menu"]',
    position: 'bottom'
  }
];

export const adminTourSteps: TourStep[] = [
  {
    id: 'welcome-chat',
    title: 'Meet Astra, Your AI Assistant',
    description: 'Type any question here and I\'ll help you find answers from your team\'s data. Try asking me to create visualizations or search through your documents!',
    targetSelector: '[data-tour="chat-input"]',
    position: 'top'
  },
  {
    id: 'chat-modes',
    title: 'Private or Team Chat',
    description: 'Use Private mode for personal questions that only you can see. Switch to Team mode when you want everyone to collaborate on insights together.',
    targetSelector: '[data-tour="mode-toggle"]',
    position: 'bottom'
  },
  {
    id: 'reports-view',
    title: 'View Team Reports',
    description: 'Access scheduled reports and insights. As an admin, you can set up automated reports that run daily, weekly, or monthly from Team Settings.',
    targetSelector: '[data-tour="reports-button"]',
    position: 'right'
  },
  {
    id: 'team-members',
    title: 'Manage Your Team',
    description: 'View all team members here. As an admin, you can invite new members, manage roles, and remove users from your team.',
    targetSelector: '[data-tour="team-panel"]',
    position: 'left'
  },
  {
    id: 'user-settings',
    title: 'Team Settings & Profile',
    description: 'Access team settings to connect Google Drive, set up scheduled reports, and manage team configuration. You can also update your personal profile here.',
    targetSelector: '[data-tour="user-menu"]',
    position: 'bottom'
  },
  {
    id: 'visualizations',
    title: 'Data Visualizations',
    description: 'Ask me to create charts and visualizations! Your visualizations are private to you, even in Team mode. Save your favorites or export them as PDFs.',
    targetSelector: '[data-tour="chat-input"]',
    position: 'top'
  }
];

export function getTourStepsForRole(isAdmin: boolean): TourStep[] {
  return isAdmin ? adminTourSteps : memberTourSteps;
}
